# Deplacement
PIN_TRIG = None
PIN_ECHO = None

PIN_LEFT_MOTOR = None
PIN_RIGHT_MOTOR = None

TURN_TIME = 5

# Elevation
PIN_TRIG_ELEVATION = None
PIN_ECHO_ELEVATION = None

PIN_ELEVATION_ROTATION_ONE = None
PIN_ELEVATION_ROTATION_TWO = None
